#!/usr/bin/env python3
"""Measure what each dataset knows about a sample of 20 passages.

  python scripts/coverage.py            writes data/COVERAGE.md

The sample is 16 verses drawn (fixed seed) from the references already found in
out/<topic>.fr.json, plus 4 fixed passages chosen for their dates and speakers.
For each passage: is there a date, a place, a speaker, according to each dataset?
"""
import json
import random
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

import datasets as ds  # noqa: E402
from books import BOOKS, NAMES  # noqa: E402

FIXED = ["JHN.14.6", "JHN.18.38", "ACT.2.1", "JHN.19.14"]
SEED = 7
NAME_TO_CODE = {v: k for k, v in NAMES.items()}
_FR_REF = re.compile(r"^(.+?) (\d+),(\d+)")


def parse_fr_reference(ref: str):
    """'Matthieu 5,18' -> 'MAT.5.18' (first verse of a range), or None."""
    m = _FR_REF.match(ref or "")
    if not m or m.group(1) not in NAME_TO_CODE:
        return None
    return f"{NAME_TO_CODE[m.group(1)]}.{int(m.group(2))}.{int(m.group(3))}"


def sample_passages(candidates: list, fixed: list = FIXED, n: int = 20, seed: int = SEED) -> list:
    """The fixed passages first, then a seeded random draw from the candidates up to n in all."""
    pool = sorted(set(candidates) - set(fixed))
    rng = random.Random(seed)
    return list(fixed) + rng.sample(pool, min(n - len(fixed), len(pool)))


def covered(passage_rows: list, field: str) -> int:
    return sum(1 for r in passage_rows if r[field])


def measure(passages: list, th: dict, ob: dict, speakers: list, acai: dict) -> list:
    rows = []
    for vid in passages:
        key = ds.verse_key(vid)
        events = th["events"].get(key, [])
        rows.append({
            "id": vid,
            "theo_dates": [f"{e['year']} ({e['precision']})" for e in events],
            "theo_places": [p["name"] for p in th["places"].get(key, [])],
            "theo_event_places": [name for e in events for name in e["places"]],
            "ob_places": [f"{p['name']} [{p['score']}]" for p in ob.get(key, [])],
            "speakers": ds.speakers_at(speakers, key),
            "acai_people": [e["label"] for e in acai["people"].get(key, [])],
            "acai_places": [e["label"] for e in acai["places"].get(key, [])],
        })
    return rows


def _cell(items: list, show: int = 2) -> str:
    if not items:
        return "-"
    uniq = list(dict.fromkeys(items))
    extra = f" +{len(uniq) - show}" if len(uniq) > show else ""
    return ", ".join(uniq[:show]) + extra


def render(rows: list, lock: dict) -> str:
    cols = [("theo_dates", "Theographic: date (year)"), ("theo_places", "Theographic: places in verse"),
            ("theo_event_places", "Theographic: event places"), ("ob_places", "OpenBible: places [score]"), ("speakers", "speaker-quotations: speaker"),
            ("acai_people", "ACAI: people"), ("acai_places", "ACAI: places")]
    out = ["# Dataset coverage on 20 passages", "",
           "Generated by `python scripts/coverage.py`. A cell shows the first two items found, `-` means nothing.",
           "Dates are years as read from the dataset (BCE negative); the precision in brackets is the one the dataset gives.",
           "OpenBible scores are the published `vote_average` of the best identification (0 to 1000 scale as published).",
           "", "Pinned commits: " + ", ".join(f"{k} `{v['commit'][:10]}`" for k, v in sorted(lock.items())), "",
           "| Passage | " + " | ".join(label for _, label in cols) + " |",
           "|---|" + "---|" * len(cols)]
    for r in rows:
        out.append(f"| {r['id']} | " + " | ".join(_cell(r[c]) for c, _ in cols) + " |")
    out += ["", "## Summary", "", "| Dataset and field | Passages covered |", "|---|---|"]
    for c, label in cols:
        out.append(f"| {label} | {covered(rows, c)}/{len(rows)} |")
    out.append("")
    return "\n".join(out)


def main() -> int:
    refs = []
    for f in sorted((ROOT / "out").glob("*.fr.json")):
        refs += [parse_fr_reference(e.get("reference", "")) for e in json.loads(f.read_text(encoding="utf-8"))]
    refs = [r for r in refs if r]
    passages = sample_passages(refs)
    th, ob = ds.load_theographic(), ds.load_openbible()
    speakers, acai = ds.load_speakers(), ds.load_acai()
    rows = measure(passages, th, ob, speakers, acai)
    lock = json.loads((ROOT / "data" / "sources.lock.json").read_text(encoding="utf-8"))
    text = render(rows, lock)
    (ROOT / "data" / "COVERAGE.md").write_text(text, encoding="utf-8")
    print(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
